<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net472-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <OutputType>Library</OutputType>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)ExtLibs\BaseClasses\BaseClasses.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\BSE.Windows.Forms\BSE.Windows.Forms.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\Core\Core.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\Mavlink\MAVLink.csproj" />
    <ProjectReference Include="$(SolutionDir)MissionPlanner.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\ArduPilot\MissionPlanner.ArduPilot.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\Comms\MissionPlanner.Comms.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\Controls\MissionPlanner.Controls.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\GeoUtility\GeoUtility.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\GMap.NET.Core\GMap.NET.Core.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\GMap.NET.WindowsForms\GMap.NET.WindowsForms.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\Utilities\MissionPlanner.Utilities.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\GMap.NET.Drawing\GMap.NET.Drawing.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\Interfaces\Interfaces.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\Maps\MissionPlanner.Maps.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\MissionPlanner.Drawing\MissionPlanner.Drawing.csproj" />
    <ProjectReference Include="$(SolutionDir)ExtLibs\SvgNet\SvgNet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.7" />
  </ItemGroup>
</Project>